[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = []

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.2"
hooks = [
  { id = "ruff-check", args = [
    "--fix",
  ], types_or = [
    "python",
    "pyi",
  ] },
  { id = "ruff-format", types_or = [
    "python",
    "pyi",
  ] },
]

[[repos]]
repo = "local"
hooks = [
  { id = "oxlint", name = "oxlint", language = "system", entry = "npx oxlint", types_or = [
    "javascript",
    "jsx",
    "ts",
    "tsx",
  ] },
  { id = "oxfmt", name = "oxfmt", language = "system", entry = "npx oxfmt --no-error-on-unmatched-pattern", types_or = [
    "javascript",
    "jsx",
    "ts",
    "tsx",
    "json",
    "yaml",
    "toml",
    "html",
    "vue",
    "css",
    "scss",
    "less",
    "markdown",
    "graphql",
  ] },
]
