# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SourceType


class AddSource(BaseModel):
    create_source: Optional["AddSourceCreateSource"] = Field(alias="createSource")


class AddSourceCreateSource(BaseModel):
    source: Optional["AddSourceCreateSourceSource"]


class AddSourceCreateSourceSource(BaseModel):
    id: str
    type: SourceType


AddSource.model_rebuild()
AddSourceCreateSource.model_rebuild()
