# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddItem(BaseModel):
    create_item: Optional["AddItemCreateItem"] = Field(alias="createItem")


class AddItemCreateItem(BaseModel):
    item: Optional["AddItemCreateItemItem"]


class AddItemCreateItemItem(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]


AddItem.model_rebuild()
AddItemCreateItem.model_rebuild()
