# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class AddVariant(BaseModel):
    create_variant: Optional["AddVariantCreateVariant"] = Field(alias="createVariant")


class AddVariantCreateVariant(BaseModel):
    variant: Optional["AddVariantCreateVariantVariant"]


class AddVariantCreateVariantVariant(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


AddVariant.model_rebuild()
AddVariantCreateVariant.model_rebuild()
