# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddOrg(BaseModel):
    create_org: Optional["AddOrgCreateOrg"] = Field(alias="createOrg")


class AddOrgCreateOrg(BaseModel):
    org: Optional["AddOrgCreateOrgOrg"]


class AddOrgCreateOrgOrg(BaseModel):
    id: str
    name: str
    desc: Optional[str]
    slug: str


AddOrg.model_rebuild()
AddOrgCreateOrg.model_rebuild()
