# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Dict, Optional, Union

from .add_variant import AddVariant
from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .get_root_category import GetRootCategory
from .get_variant import GetVariant
from .input_types import CreateVariantInput, UpdateVariantInput
from .update_variant import UpdateVariant


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def get_root_category(self, **kwargs: Any) -> GetRootCategory:
        query = gql(
            """
            query GetRootCategory {
              rootCategory {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetRootCategory", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetRootCategory.model_validate(data)

    def get_variant(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetVariant:
        query = gql(
            """
            query GetVariant($first: Int, $after: String) {
              getVariants(first: $first, after: $after) {
                edges {
                  node {
                    id
                    name
                    desc
                    created_at
                    updated_at
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"first": first, "after": after}
        response = self.execute(
            query=query, operation_name="GetVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetVariant.model_validate(data)

    def add_variant(self, input: CreateVariantInput, **kwargs: Any) -> AddVariant:
        query = gql(
            """
            mutation AddVariant($input: CreateVariantInput!) {
              createVariant(input: $input) {
                variant {
                  id
                  name
                  desc
                  created_at
                  updated_at
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddVariant.model_validate(data)

    def update_variant(self, input: UpdateVariantInput, **kwargs: Any) -> UpdateVariant:
        query = gql(
            """
            mutation UpdateVariant($input: UpdateVariantInput!) {
              updateVariant(input: $input) {
                variant {
                  id
                  name
                  desc
                  created_at
                  updated_at
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateVariant.model_validate(data)
