# Generated by ariadne-codegen
# Source: src/graphql/schema.gql

from enum import Enum


class CacheControlScope(str, Enum):
    PRIVATE = "PRIVATE"
    PUBLIC = "PUBLIC"


class ChangeStatus(str, Enum):
    APPROVED = "APPROVED"
    DRAFT = "DRAFT"
    MERGED = "MERGED"
    PROPOSED = "PROPOSED"
    REJECTED = "REJECTED"


class EditModelType(str, Enum):
    Category = "Category"
    Component = "Component"
    Item = "Item"
    Material = "Material"
    Place = "Place"
    Process = "Process"
    Region = "Region"
    Variant = "Variant"


class SearchType(str, Enum):
    CATEGORY = "CATEGORY"
    COMPONENT = "COMPONENT"
    ITEM = "ITEM"
    MATERIAL = "MATERIAL"
    ORG = "ORG"
    PLACE = "PLACE"
    REGION = "REGION"
    VARIANT = "VARIANT"


class SourceType(str, Enum):
    API = "API"
    FILE = "FILE"
    IMAGE = "IMAGE"
    OTHER = "OTHER"
    PDF = "PDF"
    TEXT = "TEXT"
    URL = "URL"
    VIDEO = "VIDEO"


class StreamScoreRating(str, Enum):
    EXCELLENT = "EXCELLENT"
    FAIR = "FAIR"
    GOOD = "GOOD"
    POOR = "POOR"
    UNKNOWN = "UNKNOWN"
    VERY_GOOD = "VERY_GOOD"


class TagType(str, Enum):
    COMPONENT = "COMPONENT"
    ITEM = "ITEM"
    ORG = "ORG"
    PLACE = "PLACE"
    PROCESS = "PROCESS"
    VARIANT = "VARIANT"
