# Generated by ariadne-codegen
# Source: src/graphql/schema.gql

from enum import Enum


class CacheControlScope(str, Enum):
    PRIVATE = "PRIVATE"
    PUBLIC = "PUBLIC"


class ChangeStatus(str, Enum):
    APPROVED = "APPROVED"
    DRAFT = "DRAFT"
    MERGED = "MERGED"
    PROPOSED = "PROPOSED"
    REJECTED = "REJECTED"


class SourceType(str, Enum):
    API = "API"
    FILE = "FILE"
    IMAGE = "IMAGE"
    OTHER = "OTHER"
    PDF = "PDF"
    TEXT = "TEXT"
    URL = "URL"
    VIDEO = "VIDEO"


class TagType(str, Enum):
    COMPONENT = "COMPONENT"
    ITEM = "ITEM"
    PLACE = "PLACE"
    PROCESS = "PROCESS"
    VARIANT = "VARIANT"
