# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetOrg(BaseModel):
    get_org: Optional["GetOrgGetOrg"] = Field(alias="getOrg")


class GetOrgGetOrg(BaseModel):
    id: str
    name: str
    desc: Optional[str]
    slug: str


GetOrg.model_rebuild()
