# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SourceType


class GetSource(BaseModel):
    source: Optional["GetSourceSource"]


class GetSourceSource(BaseModel):
    id: str
    type: SourceType
    processed_at: Optional[Any] = Field(alias="processedAt")
    location: Optional[str]
    content: Optional[Any]
    content_url: Optional[str] = Field(alias="contentURL")
    metadata: Optional[Any]


GetSource.model_rebuild()
