# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SourceType


class GetSource(BaseModel):
    get_source: Optional["GetSourceGetSource"] = Field(alias="getSource")


class GetSourceGetSource(BaseModel):
    id: str
    type: SourceType
    processed_at: Optional[Any]
    location: Optional[str]
    content: Optional[Any]
    content_url: Optional[str]
    metadata: Optional[Any]


GetSource.model_rebuild()
