# Generated by ariadne-codegen
# Source: src/graphql/queries

from pydantic import Field

from .base_model import BaseModel


class GetRootCategory(BaseModel):
    category_root: "GetRootCategoryCategoryRoot" = Field(alias="categoryRoot")


class GetRootCategoryCategoryRoot(BaseModel):
    id: str


GetRootCategory.model_rebuild()
