# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetSource(BaseModel):
    get_source: Optional["GetSourceGetSource"] = Field(alias="getSource")


class GetSourceGetSource(BaseModel):
    id: str


GetSource.model_rebuild()
