# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetVariant(BaseModel):
    get_variants: "GetVariantGetVariants" = Field(alias="getVariants")


class GetVariantGetVariants(BaseModel):
    edges: Optional[List["GetVariantGetVariantsEdges"]]
    page_info: "GetVariantGetVariantsPageInfo" = Field(alias="pageInfo")


class GetVariantGetVariantsEdges(BaseModel):
    node: "GetVariantGetVariantsEdgesNode"


class GetVariantGetVariantsEdgesNode(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    created_at: Any
    updated_at: Any


class GetVariantGetVariantsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


GetVariant.model_rebuild()
GetVariantGetVariants.model_rebuild()
GetVariantGetVariantsEdges.model_rebuild()
