# Generated by ariadne-codegen
# Source: src/graphql/queries

from pydantic import Field

from .base_model import BaseModel


class GetRootCategory(BaseModel):
    root_category: "GetRootCategoryRootCategory" = Field(alias="rootCategory")


class GetRootCategoryRootCategory(BaseModel):
    id: str


GetRootCategory.model_rebuild()
