# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetOrg(BaseModel):
    org: Optional["GetOrgOrg"]


class GetOrgOrg(BaseModel):
    id: str
    name: str
    desc: Optional[str]
    slug: str


GetOrg.model_rebuild()
