# Generated by ariadne-codegen
# Source: src/graphql/schema.gql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ChangeStatus, SourceType, TagType


class ComponentMaterialInput(BaseModel):
    id: str
    material_fraction: Optional[float] = None


class ComponentRegionInput(BaseModel):
    id: str


class ComponentTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


class CreateCategoryInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    desc_short: Optional[str] = None
    image_url: Optional[str] = None
    lang: Optional[str] = None
    name: str
    remove_sources: Optional[List[str]] = None


class CreateChangeInput(BaseModel):
    description: Optional[str] = None
    metadata: Optional[Any] = None
    sources: List[str] = Field(default_factory=lambda: [])
    status: Optional[ChangeStatus] = None
    title: Optional[str] = None


class CreateComponentInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    image_url: Optional[str] = None
    lang: Optional[str] = None
    materials: Optional[List["ComponentMaterialInput"]] = None
    name: str
    name_tr: Optional[List["TranslatedInput"]] = None
    primary_material: Optional["ComponentMaterialInput"] = None
    region: Optional["ComponentRegionInput"] = None
    remove_sources: Optional[List[str]] = None
    tags: Optional[List["ComponentTagsInput"]] = None


class CreateItemInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    categories: Optional[List["ItemCategoriesInput"]] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    image_url: Optional[str] = None
    lang: Optional[str] = None
    name: Optional[str] = None
    remove_sources: Optional[List[str]] = None
    tags: Optional[List["ItemTagsInput"]] = None


class CreateOrgInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    avatar_url: Optional[str] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    lang: Optional[str] = None
    name: str
    remove_sources: Optional[List[str]] = None
    slug: str
    website_url: Optional[str] = None


class CreateProcessInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    intent: str
    lang: Optional[str] = None
    material: Optional[str] = None
    name: str
    name_tr: Optional[List["TranslatedInput"]] = None
    org: Optional[str] = None
    place: Optional[str] = None
    region: Optional[str] = None
    remove_sources: Optional[List[str]] = None
    variant: Optional[str] = None


class CreateSourceInput(BaseModel):
    content: Optional[Any] = None
    content_url: Optional[str] = None
    location: Optional[str] = None
    metadata: Optional[Any] = None
    type: SourceType


class CreateTagDefinitionInput(BaseModel):
    bg_color: Optional[str] = None
    desc: Optional[str] = None
    image: Optional[str] = None
    meta_template: Optional[Any] = None
    name: str
    type: TagType


class CreateVariantInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    code: Optional[str] = None
    components: Optional[List["VariantComponentsInput"]] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    items: Optional[List["VariantItemsInput"]] = None
    lang: Optional[str] = None
    name: Optional[str] = None
    name_tr: Optional[List["TranslatedInput"]] = None
    orgs: Optional[List["VariantOrgsInput"]] = None
    region_id: Optional[str] = None
    regions: Optional[List["VariantRegionsInput"]] = None
    remove_sources: Optional[List[str]] = None
    tags: Optional[List["VariantTagsInput"]] = None


class ItemCategoriesInput(BaseModel):
    id: str


class ItemTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


class TranslatedInput(BaseModel):
    auto: bool = False
    lang: str
    text: Optional[str] = None


class UpdateChangeInput(BaseModel):
    description: Optional[str] = None
    id: str
    metadata: Optional[Any] = None
    sources: Optional[List[str]] = None
    status: Optional[ChangeStatus] = None
    title: Optional[str] = None


class UpdateComponentInput(BaseModel):
    add_sources: Optional[List[str]] = None
    add_tags: Optional[List["ComponentTagsInput"]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    id: str
    image_url: Optional[str] = None
    lang: Optional[str] = None
    materials: Optional[List["ComponentMaterialInput"]] = None
    name: Optional[str] = None
    name_tr: Optional[List["TranslatedInput"]] = None
    primary_material: Optional["ComponentMaterialInput"] = None
    region: Optional["ComponentRegionInput"] = None
    remove_sources: Optional[List[str]] = None
    remove_tags: Optional[List["ComponentTagsInput"]] = None


class UpdateItemInput(BaseModel):
    add_categories: Optional[List["ItemCategoriesInput"]] = None
    add_sources: Optional[List[str]] = None
    add_tags: Optional[List["ItemTagsInput"]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    id: str
    image_url: Optional[str] = None
    lang: Optional[str] = None
    name: Optional[str] = None
    remove_categories: Optional[List["ItemCategoriesInput"]] = None
    remove_sources: Optional[List[str]] = None
    remove_tags: Optional[List["ItemTagsInput"]] = None


class UpdateOrgInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    avatar_url: Optional[str] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    id: str
    lang: Optional[str] = None
    name: Optional[str] = None
    remove_sources: Optional[List[str]] = None
    slug: Optional[str] = None
    website_url: Optional[str] = None


class UpdateProcessInput(BaseModel):
    add_sources: Optional[List[str]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    id: str
    intent: Optional[str] = None
    lang: Optional[str] = None
    material: Optional[str] = None
    name: Optional[str] = None
    name_tr: Optional[List["TranslatedInput"]] = None
    org: Optional[str] = None
    place: Optional[str] = None
    region: Optional[str] = None
    remove_sources: Optional[List[str]] = None
    variant: Optional[str] = None


class UpdateSourceInput(BaseModel):
    content: Optional[Any] = None
    content_url: Optional[str] = None
    id: str
    location: Optional[str] = None
    metadata: Optional[Any] = None
    type: Optional[SourceType] = None


class UpdateTagDefinitionInput(BaseModel):
    bg_color: Optional[str] = None
    desc: Optional[str] = None
    id: str
    image: Optional[str] = None
    meta_template: Optional[Any] = None
    name: Optional[str] = None
    type: Optional[TagType] = None


class UpdateVariantInput(BaseModel):
    add_components: Optional[List["VariantComponentsInput"]] = None
    add_items: Optional[List["VariantItemsInput"]] = None
    add_orgs: Optional[List["VariantOrgsInput"]] = None
    add_regions: Optional[List["VariantRegionsInput"]] = None
    add_sources: Optional[List[str]] = None
    add_tags: Optional[List["VariantTagsInput"]] = None
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = None
    code: Optional[str] = None
    desc: Optional[str] = None
    desc_tr: Optional[List["TranslatedInput"]] = None
    id: str
    lang: Optional[str] = None
    name: Optional[str] = None
    name_tr: Optional[List["TranslatedInput"]] = None
    region_id: Optional[str] = None
    remove_components: Optional[List["VariantComponentsInput"]] = None
    remove_items: Optional[List["VariantItemsInput"]] = None
    remove_orgs: Optional[List["VariantOrgsInput"]] = None
    remove_regions: Optional[List["VariantRegionsInput"]] = None
    remove_sources: Optional[List[str]] = None
    remove_tags: Optional[List["VariantTagsInput"]] = None


class VariantComponentsInput(BaseModel):
    id: str
    quantity: Optional[float] = None
    unit: Optional[str] = None


class VariantItemsInput(BaseModel):
    id: str


class VariantOrgsInput(BaseModel):
    id: str


class VariantRegionsInput(BaseModel):
    id: str


class VariantTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


CreateCategoryInput.model_rebuild()
CreateComponentInput.model_rebuild()
CreateItemInput.model_rebuild()
CreateOrgInput.model_rebuild()
CreateProcessInput.model_rebuild()
CreateVariantInput.model_rebuild()
UpdateComponentInput.model_rebuild()
UpdateItemInput.model_rebuild()
UpdateOrgInput.model_rebuild()
UpdateProcessInput.model_rebuild()
UpdateVariantInput.model_rebuild()
