# Generated by ariadne-codegen
# Source: src/graphql/queries

from pydantic import Field

from .base_model import BaseModel


class RootCategory(BaseModel):
    root_category: "RootCategoryRootCategory" = Field(alias="categoryRoot")


class RootCategoryRootCategory(BaseModel):
    id: str


RootCategory.model_rebuild()
