# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateItem(BaseModel):
    update_item: Optional["UpdateItemUpdateItem"] = Field(alias="updateItem")


class UpdateItemUpdateItem(BaseModel):
    item: Optional["UpdateItemUpdateItemItem"]


class UpdateItemUpdateItemItem(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]


UpdateItem.model_rebuild()
UpdateItemUpdateItem.model_rebuild()
