# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SourceType


class UpdateSource(BaseModel):
    update_source: Optional["UpdateSourceUpdateSource"] = Field(alias="updateSource")


class UpdateSourceUpdateSource(BaseModel):
    source: Optional["UpdateSourceUpdateSourceSource"]


class UpdateSourceUpdateSourceSource(BaseModel):
    id: str
    type: SourceType
    processed_at: Optional[Any] = Field(alias="processedAt")
    location: Optional[str]


UpdateSource.model_rebuild()
UpdateSourceUpdateSource.model_rebuild()
