# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateVariant(BaseModel):
    update_variant: Optional["UpdateVariantUpdateVariant"] = Field(
        alias="updateVariant"
    )


class UpdateVariantUpdateVariant(BaseModel):
    variant: Optional["UpdateVariantUpdateVariantVariant"]


class UpdateVariantUpdateVariantVariant(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    created_at: Any
    updated_at: Any


UpdateVariant.model_rebuild()
UpdateVariantUpdateVariant.model_rebuild()
