# Generated by ariadne-codegen
# Source: src/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateOrg(BaseModel):
    update_org: Optional["UpdateOrgUpdateOrg"] = Field(alias="updateOrg")


class UpdateOrgUpdateOrg(BaseModel):
    org: Optional["UpdateOrgUpdateOrgOrg"]


class UpdateOrgUpdateOrgOrg(BaseModel):
    id: str
    name: str
    desc: Optional[str]
    slug: str


UpdateOrg.model_rebuild()
UpdateOrgUpdateOrg.model_rebuild()
