# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddProcess(BaseModel):
    create_process: Optional["AddProcessCreateProcess"] = Field(alias="createProcess")


class AddProcessCreateProcess(BaseModel):
    process: Optional["AddProcessCreateProcessProcess"]
    change: Optional["AddProcessCreateProcessChange"]


class AddProcessCreateProcessProcess(BaseModel):
    id: str
    name: Optional[str]


class AddProcessCreateProcessChange(BaseModel):
    id: str


AddProcess.model_rebuild()
AddProcessCreateProcess.model_rebuild()
