# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddCategory(BaseModel):
    create_category: Optional["AddCategoryCreateCategory"] = Field(
        alias="createCategory"
    )


class AddCategoryCreateCategory(BaseModel):
    category: Optional["AddCategoryCreateCategoryCategory"]
    change: Optional["AddCategoryCreateCategoryChange"]


class AddCategoryCreateCategoryCategory(BaseModel):
    id: str
    name: str


class AddCategoryCreateCategoryChange(BaseModel):
    id: str


AddCategory.model_rebuild()
AddCategoryCreateCategory.model_rebuild()
