# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddComponent(BaseModel):
    create_component: Optional["AddComponentCreateComponent"] = Field(
        alias="createComponent"
    )


class AddComponentCreateComponent(BaseModel):
    component: Optional["AddComponentCreateComponentComponent"]
    change: Optional["AddComponentCreateComponentChange"]


class AddComponentCreateComponentComponent(BaseModel):
    id: str
    name: Optional[str]


class AddComponentCreateComponentChange(BaseModel):
    id: str


AddComponent.model_rebuild()
AddComponentCreateComponent.model_rebuild()
