# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class AddVariant(BaseModel):
    create_variant: Optional["AddVariantCreateVariant"] = Field(alias="createVariant")


class AddVariantCreateVariant(BaseModel):
    variant: Optional["AddVariantCreateVariantVariant"]
    change: Optional["AddVariantCreateVariantChange"]


class AddVariantCreateVariantVariant(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


class AddVariantCreateVariantChange(BaseModel):
    id: str


AddVariant.model_rebuild()
AddVariantCreateVariant.model_rebuild()
