# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional, Union

from .add_category import AddCategory
from .add_component import AddComponent
from .add_item import AddItem
from .add_org import AddOrg
from .add_process import AddProcess
from .add_source import AddSource
from .add_variant import AddVariant
from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .enums import SearchType
from .get_category_for_review import GetCategoryForReview
from .get_category_schema import GetCategorySchema
from .get_change_for_review import GetChangeForReview
from .get_component_for_review import GetComponentForReview
from .get_component_schema import GetComponentSchema
from .get_current_user import GetCurrentUser
from .get_item_for_link import GetItemForLink
from .get_item_for_review import GetItemForReview
from .get_item_schema import GetItemSchema
from .get_material_for_review import GetMaterialForReview
from .get_org import GetOrg
from .get_place_for_review import GetPlaceForReview
from .get_process_for_review import GetProcessForReview
from .get_process_schema import GetProcessSchema
from .get_root_category import GetRootCategory
from .get_source import GetSource
from .get_variant import GetVariant
from .get_variant_for_review import GetVariantForReview
from .get_variant_schema import GetVariantSchema
from .input_types import (
    CreateCategoryInput,
    CreateComponentInput,
    CreateItemInput,
    CreateOrgInput,
    CreateProcessInput,
    CreateSourceInput,
    CreateVariantInput,
    LinkSourceInput,
    UpdateCategoryInput,
    UpdateChangeInput,
    UpdateComponentInput,
    UpdateItemInput,
    UpdateOrgInput,
    UpdateProcessInput,
    UpdateSourceInput,
    UpdateVariantInput,
)
from .link_source import LinkSource
from .search import Search
from .update_category import UpdateCategory
from .update_change_status import UpdateChangeStatus
from .update_component import UpdateComponent
from .update_item import UpdateItem
from .update_org import UpdateOrg
from .update_process import UpdateProcess
from .update_source import UpdateSource
from .update_variant import UpdateVariant


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def add_category(self, input: CreateCategoryInput, **kwargs: Any) -> AddCategory:
        query = gql("""
            mutation AddCategory($input: CreateCategoryInput!) {
              createCategory(input: $input) {
                category {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddCategory", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddCategory.model_validate(data)

    def update_category(
        self, input: UpdateCategoryInput, **kwargs: Any
    ) -> UpdateCategory:
        query = gql("""
            mutation UpdateCategory($input: UpdateCategoryInput!) {
              updateCategory(input: $input) {
                category {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateCategory", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateCategory.model_validate(data)

    def get_root_category(self, **kwargs: Any) -> GetRootCategory:
        query = gql("""
            query GetRootCategory {
              categoryRoot {
                id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetRootCategory", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetRootCategory.model_validate(data)

    def get_category_for_review(self, id: str, **kwargs: Any) -> GetCategoryForReview:
        query = gql("""
            query GetCategoryForReview($id: ID!) {
              category(id: $id) {
                id
                name
                desc
                parents(first: 5) {
                  nodes {
                    id
                    name
                  }
                }
                children(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
                items(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetCategoryForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetCategoryForReview.model_validate(data)

    def get_change_for_review(self, id: str, **kwargs: Any) -> GetChangeForReview:
        query = gql("""
            query GetChangeForReview($id: ID!) {
              change(id: $id) {
                id
                title
                description
                status
                user {
                  id
                  username
                }
                edits(first: 100) {
                  nodes {
                    id
                    entityName
                    createInput
                    updateInput
                    changes {
                      ... on Item {
                        __typename
                        id
                      }
                      ... on Variant {
                        __typename
                        id
                      }
                      ... on Component {
                        __typename
                        id
                      }
                      ... on Process {
                        __typename
                        id
                      }
                      ... on Place {
                        __typename
                        id
                      }
                      ... on Category {
                        __typename
                        id
                      }
                      ... on Material {
                        __typename
                        id
                      }
                      ... on Region {
                        __typename
                        id
                      }
                    }
                    original {
                      ... on Item {
                        __typename
                        id
                      }
                      ... on Variant {
                        __typename
                        id
                      }
                      ... on Component {
                        __typename
                        id
                      }
                      ... on Process {
                        __typename
                        id
                      }
                      ... on Place {
                        __typename
                        id
                      }
                      ... on Category {
                        __typename
                        id
                      }
                      ... on Material {
                        __typename
                        id
                      }
                      ... on Region {
                        __typename
                        id
                      }
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetChangeForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetChangeForReview.model_validate(data)

    def update_change_status(
        self, input: UpdateChangeInput, **kwargs: Any
    ) -> UpdateChangeStatus:
        query = gql("""
            mutation UpdateChangeStatus($input: UpdateChangeInput!) {
              updateChange(input: $input) {
                change {
                  id
                  status
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query,
            operation_name="UpdateChangeStatus",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return UpdateChangeStatus.model_validate(data)

    def get_component_for_review(self, id: str, **kwargs: Any) -> GetComponentForReview:
        query = gql("""
            query GetComponentForReview($id: ID!) {
              component(id: $id) {
                id
                name
                desc
                primaryMaterial {
                  id
                  name
                }
                materials {
                  material {
                    id
                    name
                  }
                  materialFraction
                }
                sources(first: 10) {
                  nodes {
                    source {
                      id
                      content
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetComponentForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetComponentForReview.model_validate(data)

    def add_component(self, input: CreateComponentInput, **kwargs: Any) -> AddComponent:
        query = gql("""
            mutation AddComponent($input: CreateComponentInput!) {
              createComponent(input: $input) {
                component {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddComponent", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddComponent.model_validate(data)

    def update_component(
        self, input: UpdateComponentInput, **kwargs: Any
    ) -> UpdateComponent:
        query = gql("""
            mutation UpdateComponent($input: UpdateComponentInput!) {
              updateComponent(input: $input) {
                component {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateComponent", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateComponent.model_validate(data)

    def get_item_for_review(self, id: str, **kwargs: Any) -> GetItemForReview:
        query = gql("""
            query GetItemForReview($id: ID!) {
              item(id: $id) {
                id
                name
                desc
                categories(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
                variants(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetItemForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetItemForReview.model_validate(data)

    def get_item_for_link(self, id: str, **kwargs: Any) -> GetItemForLink:
        query = gql("""
            query GetItemForLink($id: ID!) {
              item(id: $id) {
                id
                name
                desc
                categories(first: 5) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query, operation_name="GetItemForLink", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetItemForLink.model_validate(data)

    def add_item(self, input: CreateItemInput, **kwargs: Any) -> AddItem:
        query = gql("""
            mutation AddItem($input: CreateItemInput!) {
              createItem(input: $input) {
                item {
                  id
                  name
                  desc
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddItem", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddItem.model_validate(data)

    def update_item(self, input: UpdateItemInput, **kwargs: Any) -> UpdateItem:
        query = gql("""
            mutation UpdateItem($input: UpdateItemInput!) {
              updateItem(input: $input) {
                item {
                  id
                  name
                  desc
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateItem", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateItem.model_validate(data)

    def get_material_for_review(self, id: str, **kwargs: Any) -> GetMaterialForReview:
        query = gql("""
            query GetMaterialForReview($id: ID!) {
              material(id: $id) {
                id
                name
                desc
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetMaterialForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetMaterialForReview.model_validate(data)

    def get_org(self, org_id: str, **kwargs: Any) -> GetOrg:
        query = gql("""
            query GetOrg($orgId: ID!) {
              org(id: $orgId) {
                id
                name
                desc
                slug
              }
            }
            """)
        variables: dict[str, object] = {"orgId": org_id}
        response = self.execute(
            query=query, operation_name="GetOrg", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetOrg.model_validate(data)

    def add_org(self, input: CreateOrgInput, **kwargs: Any) -> AddOrg:
        query = gql("""
            mutation AddOrg($input: CreateOrgInput!) {
              createOrg(input: $input) {
                org {
                  id
                  name
                  desc
                  slug
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddOrg", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddOrg.model_validate(data)

    def update_org(self, input: UpdateOrgInput, **kwargs: Any) -> UpdateOrg:
        query = gql("""
            mutation UpdateOrg($input: UpdateOrgInput!) {
              updateOrg(input: $input) {
                org {
                  id
                  name
                  desc
                  slug
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateOrg", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateOrg.model_validate(data)

    def get_place_for_review(self, id: str, **kwargs: Any) -> GetPlaceForReview:
        query = gql("""
            query GetPlaceForReview($id: ID!) {
              place(id: $id) {
                id
                name
                desc
                address {
                  street
                  housenumber
                  city
                  postalCode
                  region
                  country
                }
                location {
                  latitude
                  longitude
                }
                org {
                  id
                  name
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetPlaceForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetPlaceForReview.model_validate(data)

    def add_process(self, input: CreateProcessInput, **kwargs: Any) -> AddProcess:
        query = gql("""
            mutation AddProcess($input: CreateProcessInput!) {
              createProcess(input: $input) {
                process {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddProcess", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddProcess.model_validate(data)

    def update_process(self, input: UpdateProcessInput, **kwargs: Any) -> UpdateProcess:
        query = gql("""
            mutation UpdateProcess($input: UpdateProcessInput!) {
              updateProcess(input: $input) {
                process {
                  id
                  name
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateProcess", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateProcess.model_validate(data)

    def get_process_for_review(self, id: str, **kwargs: Any) -> GetProcessForReview:
        query = gql("""
            query GetProcessForReview($id: ID!) {
              process(id: $id) {
                id
                name
                desc
                intent
                material {
                  id
                  name
                }
                org {
                  id
                  name
                }
                place {
                  id
                  name
                }
                region {
                  id
                }
                variant {
                  id
                  name
                }
                efficiency {
                  efficiency
                  equivalency
                  valueRatio
                }
                sources(first: 10) {
                  nodes {
                    source {
                      id
                      content
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetProcessForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetProcessForReview.model_validate(data)

    def get_variant_schema(self, **kwargs: Any) -> GetVariantSchema:
        query = gql("""
            query GetVariantSchema {
              variantSchema {
                create {
                  schema
                }
                update {
                  schema
                }
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetVariantSchema",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetVariantSchema.model_validate(data)

    def get_item_schema(self, **kwargs: Any) -> GetItemSchema:
        query = gql("""
            query GetItemSchema {
              itemSchema {
                create {
                  schema
                }
                update {
                  schema
                }
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetItemSchema", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetItemSchema.model_validate(data)

    def get_category_schema(self, **kwargs: Any) -> GetCategorySchema:
        query = gql("""
            query GetCategorySchema {
              categorySchema {
                create {
                  schema
                }
                update {
                  schema
                }
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetCategorySchema",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetCategorySchema.model_validate(data)

    def get_component_schema(self, **kwargs: Any) -> GetComponentSchema:
        query = gql("""
            query GetComponentSchema {
              componentSchema {
                create {
                  schema
                }
                update {
                  schema
                }
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetComponentSchema",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetComponentSchema.model_validate(data)

    def get_process_schema(self, **kwargs: Any) -> GetProcessSchema:
        query = gql("""
            query GetProcessSchema {
              processSchema {
                create {
                  schema
                }
                update {
                  schema
                }
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetProcessSchema",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetProcessSchema.model_validate(data)

    def search(
        self,
        query: str,
        types: Union[Optional[list[SearchType]], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> Search:
        _query = gql("""
            query Search($query: String!, $types: [SearchType!], $limit: Int) {
              search(query: $query, types: $types, limit: $limit) {
                nodes {
                  __typename
                  ... on Variant {
                    id
                    name
                    desc
                    imageURL
                  }
                  ... on Item {
                    id
                    name
                    desc
                    imageURL
                  }
                  ... on Component {
                    id
                    name
                    desc
                    imageURL
                  }
                  ... on Category {
                    id
                    label: name
                    desc
                    descShort
                    imageURL
                  }
                  ... on Org {
                    id
                    label: name
                    desc
                    slug
                    websiteURL
                  }
                  ... on Place {
                    id
                    name
                    desc
                  }
                  ... on Region {
                    id
                    name
                    placetype
                  }
                  ... on Material {
                    id
                    name
                    desc
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"query": query, "types": types, "limit": limit}
        response = self.execute(
            query=_query, operation_name="Search", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Search.model_validate(data)

    def get_source(self, id: str, **kwargs: Any) -> GetSource:
        query = gql("""
            query GetSource($id: ID!) {
              source(id: $id) {
                id
                type
                processedAt
                location
                content
                contentURL
                metadata
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query, operation_name="GetSource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetSource.model_validate(data)

    def add_source(self, input: CreateSourceInput, **kwargs: Any) -> AddSource:
        query = gql("""
            mutation AddSource($input: CreateSourceInput!) {
              createSource(input: $input) {
                source {
                  id
                  type
                  processedAt
                  location
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddSource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddSource.model_validate(data)

    def update_source(self, input: UpdateSourceInput, **kwargs: Any) -> UpdateSource:
        query = gql("""
            mutation UpdateSource($input: UpdateSourceInput!) {
              updateSource(input: $input) {
                source {
                  id
                  type
                  processedAt
                  location
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateSource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateSource.model_validate(data)

    def link_source(self, input: LinkSourceInput, **kwargs: Any) -> LinkSource:
        query = gql("""
            mutation LinkSource($input: LinkSourceInput!) {
              linkSource(input: $input) {
                source {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="LinkSource", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return LinkSource.model_validate(data)

    def get_current_user(self, **kwargs: Any) -> GetCurrentUser:
        query = gql("""
            query GetCurrentUser {
              me {
                id
                email
                name
                username
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetCurrentUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetCurrentUser.model_validate(data)

    def get_variant_for_review(self, id: str, **kwargs: Any) -> GetVariantForReview:
        query = gql("""
            query GetVariantForReview($id: ID!) {
              variant(id: $id) {
                id
                name
                desc
                items(first: 10) {
                  nodes {
                    id
                    name
                    desc
                  }
                }
                components(first: 10) {
                  nodes {
                    component {
                      id
                      name
                    }
                    quantity
                    unit
                  }
                }
                orgs(first: 5) {
                  nodes {
                    org {
                      id
                      name
                    }
                    role
                  }
                }
                sources(first: 10) {
                  nodes {
                    source {
                      id
                      content
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = self.execute(
            query=query,
            operation_name="GetVariantForReview",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetVariantForReview.model_validate(data)

    def get_variant(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> GetVariant:
        query = gql("""
            query GetVariant($first: Int, $after: String) {
              variants(first: $first, after: $after) {
                edges {
                  node {
                    id
                    name
                    desc
                    createdAt
                    updatedAt
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
            """)
        variables: dict[str, object] = {"first": first, "after": after}
        response = self.execute(
            query=query, operation_name="GetVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetVariant.model_validate(data)

    def add_variant(self, input: CreateVariantInput, **kwargs: Any) -> AddVariant:
        query = gql("""
            mutation AddVariant($input: CreateVariantInput!) {
              createVariant(input: $input) {
                variant {
                  id
                  name
                  desc
                  createdAt
                  updatedAt
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="AddVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddVariant.model_validate(data)

    def update_variant(self, input: UpdateVariantInput, **kwargs: Any) -> UpdateVariant:
        query = gql("""
            mutation UpdateVariant($input: UpdateVariantInput!) {
              updateVariant(input: $input) {
                variant {
                  id
                  name
                  desc
                  createdAt
                  updatedAt
                }
                change {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = self.execute(
            query=query, operation_name="UpdateVariant", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateVariant.model_validate(data)
