# Generated by ariadne-codegen
# Source: f/graphql/schema.gql

from enum import Enum


class CacheControlScope(str, Enum):
    PRIVATE = "PRIVATE"
    PUBLIC = "PUBLIC"


class CaveatLevel(str, Enum):
    HIGH = "HIGH"
    LOW = "LOW"
    MEDIUM = "MEDIUM"


class ChangeStatus(str, Enum):
    APPROVED = "APPROVED"
    DRAFT = "DRAFT"
    MERGED = "MERGED"
    PROPOSED = "PROPOSED"
    REJECTED = "REJECTED"


class EditModelType(str, Enum):
    Category = "Category"
    Component = "Component"
    Item = "Item"
    Material = "Material"
    Org = "Org"
    Place = "Place"
    Process = "Process"
    Program = "Program"
    Variant = "Variant"


class FeedFormat(str, Enum):
    ANNOUNCEMENT = "ANNOUNCEMENT"
    ARTICLE = "ARTICLE"
    EXTERNAL = "EXTERNAL"
    FEATURE = "FEATURE"
    PROJECT = "PROJECT"
    UPDATE = "UPDATE"


class SearchType(str, Enum):
    CATEGORY = "CATEGORY"
    COMPONENT = "COMPONENT"
    ITEM = "ITEM"
    MATERIAL = "MATERIAL"
    ORG = "ORG"
    PLACE = "PLACE"
    REGION = "REGION"
    VARIANT = "VARIANT"


class SourceType(str, Enum):
    API = "API"
    FILE = "FILE"
    IMAGE = "IMAGE"
    OTHER = "OTHER"
    PDF = "PDF"
    TEXT = "TEXT"
    URL = "URL"
    VIDEO = "VIDEO"


class StreamScoreRating(str, Enum):
    A = "A"
    A_PLUS = "A_PLUS"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    F = "F"
    G = "G"
    UNKNOWN = "UNKNOWN"


class TagType(str, Enum):
    COMPONENT = "COMPONENT"
    ITEM = "ITEM"
    ORG = "ORG"
    PLACE = "PLACE"
    PROCESS = "PROCESS"
    PROGRAM = "PROGRAM"
    VARIANT = "VARIANT"
