# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetItemSchema(BaseModel):
    item_schema: Optional["GetItemSchemaItemSchema"] = Field(alias="itemSchema")


class GetItemSchemaItemSchema(BaseModel):
    create: Optional["GetItemSchemaItemSchemaCreate"]
    update: Optional["GetItemSchemaItemSchemaUpdate"]


class GetItemSchemaItemSchemaCreate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


class GetItemSchemaItemSchemaUpdate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


GetItemSchema.model_rebuild()
GetItemSchemaItemSchema.model_rebuild()
