# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetItemForLink(BaseModel):
    item: Optional["GetItemForLinkItem"]


class GetItemForLinkItem(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    categories: "GetItemForLinkItemCategories"


class GetItemForLinkItemCategories(BaseModel):
    nodes: list["GetItemForLinkItemCategoriesNodes"]


class GetItemForLinkItemCategoriesNodes(BaseModel):
    id: str
    name: str


GetItemForLink.model_rebuild()
GetItemForLinkItem.model_rebuild()
GetItemForLinkItemCategories.model_rebuild()
