# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetPlaceForReview(BaseModel):
    place: Optional["GetPlaceForReviewPlace"]


class GetPlaceForReviewPlace(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    address: Optional["GetPlaceForReviewPlaceAddress"]
    location: Optional["GetPlaceForReviewPlaceLocation"]
    org: Optional["GetPlaceForReviewPlaceOrg"]


class GetPlaceForReviewPlaceAddress(BaseModel):
    street: Optional[str]
    housenumber: Optional[str]
    city: Optional[str]
    postcode: Optional[str]
    region: Optional[str]
    country: Optional[str]


class GetPlaceForReviewPlaceLocation(BaseModel):
    latitude: float
    longitude: float


class GetPlaceForReviewPlaceOrg(BaseModel):
    id: str
    name: str


GetPlaceForReview.model_rebuild()
GetPlaceForReviewPlace.model_rebuild()
