# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetProcessForReview(BaseModel):
    process: Optional["GetProcessForReviewProcess"]


class GetProcessForReviewProcess(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    intent: str
    material: Optional["GetProcessForReviewProcessMaterial"]
    org: Optional["GetProcessForReviewProcessOrg"]
    place: Optional["GetProcessForReviewProcessPlace"]
    region: Optional["GetProcessForReviewProcessRegion"]
    variant: Optional["GetProcessForReviewProcessVariant"]
    efficiency: Optional["GetProcessForReviewProcessEfficiency"]
    sources: "GetProcessForReviewProcessSources"


class GetProcessForReviewProcessMaterial(BaseModel):
    id: str
    name: Optional[str]


class GetProcessForReviewProcessOrg(BaseModel):
    id: str
    name: str


class GetProcessForReviewProcessPlace(BaseModel):
    id: str
    name: Optional[str]


class GetProcessForReviewProcessRegion(BaseModel):
    id: str


class GetProcessForReviewProcessVariant(BaseModel):
    id: str
    name: Optional[str]


class GetProcessForReviewProcessEfficiency(BaseModel):
    efficiency: Optional[float]
    equivalency: Optional[float]
    value_ratio: Optional[float] = Field(alias="valueRatio")


class GetProcessForReviewProcessSources(BaseModel):
    nodes: Optional[list["GetProcessForReviewProcessSourcesNodes"]]


class GetProcessForReviewProcessSourcesNodes(BaseModel):
    source: "GetProcessForReviewProcessSourcesNodesSource"


class GetProcessForReviewProcessSourcesNodesSource(BaseModel):
    id: str
    content: Optional[Any]


GetProcessForReview.model_rebuild()
GetProcessForReviewProcess.model_rebuild()
GetProcessForReviewProcessSources.model_rebuild()
GetProcessForReviewProcessSourcesNodes.model_rebuild()
