# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetComponentForReview(BaseModel):
    component: Optional["GetComponentForReviewComponent"]


class GetComponentForReviewComponent(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    primary_material: "GetComponentForReviewComponentPrimaryMaterial" = Field(
        alias="primaryMaterial"
    )
    materials: list["GetComponentForReviewComponentMaterials"]


class GetComponentForReviewComponentPrimaryMaterial(BaseModel):
    id: str
    name: Optional[str]


class GetComponentForReviewComponentMaterials(BaseModel):
    material: "GetComponentForReviewComponentMaterialsMaterial"
    material_fraction: Optional[float] = Field(alias="materialFraction")


class GetComponentForReviewComponentMaterialsMaterial(BaseModel):
    id: str
    name: Optional[str]


GetComponentForReview.model_rebuild()
GetComponentForReviewComponent.model_rebuild()
GetComponentForReviewComponentMaterials.model_rebuild()
