# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetVariantSchema(BaseModel):
    variant_schema: Optional["GetVariantSchemaVariantSchema"] = Field(
        alias="variantSchema"
    )


class GetVariantSchemaVariantSchema(BaseModel):
    create: Optional["GetVariantSchemaVariantSchemaCreate"]
    update: Optional["GetVariantSchemaVariantSchemaUpdate"]


class GetVariantSchemaVariantSchemaCreate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


class GetVariantSchemaVariantSchemaUpdate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


GetVariantSchema.model_rebuild()
GetVariantSchemaVariantSchema.model_rebuild()
