# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetProcessSchema(BaseModel):
    process_schema: Optional["GetProcessSchemaProcessSchema"] = Field(
        alias="processSchema"
    )


class GetProcessSchemaProcessSchema(BaseModel):
    create: Optional["GetProcessSchemaProcessSchemaCreate"]
    update: Optional["GetProcessSchemaProcessSchemaUpdate"]


class GetProcessSchemaProcessSchemaCreate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


class GetProcessSchemaProcessSchemaUpdate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


GetProcessSchema.model_rebuild()
GetProcessSchemaProcessSchema.model_rebuild()
