# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Annotated, Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import ChangeStatus


class GetChangeForReview(BaseModel):
    change: Optional["GetChangeForReviewChange"]


class GetChangeForReviewChange(BaseModel):
    id: str
    title: Optional[str]
    description: Optional[str]
    status: ChangeStatus
    user: "GetChangeForReviewChangeUser"
    edits: "GetChangeForReviewChangeEdits"


class GetChangeForReviewChangeUser(BaseModel):
    id: str
    username: str


class GetChangeForReviewChangeEdits(BaseModel):
    nodes: Optional[list["GetChangeForReviewChangeEditsNodes"]]


class GetChangeForReviewChangeEditsNodes(BaseModel):
    id: Optional[str]
    entity_name: str = Field(alias="entityName")
    create_input: Optional[Any] = Field(alias="createInput")
    update_input: Optional[Any] = Field(alias="updateInput")
    changes: Optional[
        Annotated[
            Union[
                "GetChangeForReviewChangeEditsNodesChangesCategory",
                "GetChangeForReviewChangeEditsNodesChangesComponent",
                "GetChangeForReviewChangeEditsNodesChangesItem",
                "GetChangeForReviewChangeEditsNodesChangesMaterial",
                "GetChangeForReviewChangeEditsNodesChangesOrg",
                "GetChangeForReviewChangeEditsNodesChangesPlace",
                "GetChangeForReviewChangeEditsNodesChangesProcess",
                "GetChangeForReviewChangeEditsNodesChangesProgram",
                "GetChangeForReviewChangeEditsNodesChangesVariant",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    original: Optional[
        Annotated[
            Union[
                "GetChangeForReviewChangeEditsNodesOriginalCategory",
                "GetChangeForReviewChangeEditsNodesOriginalComponent",
                "GetChangeForReviewChangeEditsNodesOriginalItem",
                "GetChangeForReviewChangeEditsNodesOriginalMaterial",
                "GetChangeForReviewChangeEditsNodesOriginalOrg",
                "GetChangeForReviewChangeEditsNodesOriginalPlace",
                "GetChangeForReviewChangeEditsNodesOriginalProcess",
                "GetChangeForReviewChangeEditsNodesOriginalProgram",
                "GetChangeForReviewChangeEditsNodesOriginalVariant",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class GetChangeForReviewChangeEditsNodesChangesCategory(BaseModel):
    typename__: Literal["Category"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesComponent(BaseModel):
    typename__: Literal["Component"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesItem(BaseModel):
    typename__: Literal["Item"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesMaterial(BaseModel):
    typename__: Literal["Material"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesOrg(BaseModel):
    typename__: Literal["Org"] = Field(alias="__typename")


class GetChangeForReviewChangeEditsNodesChangesPlace(BaseModel):
    typename__: Literal["Place"] = Field(alias="__typename")
    typename__: Literal["Place"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesProcess(BaseModel):
    typename__: Literal["Process"] = Field(alias="__typename")
    typename__: Literal["Process"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesChangesProgram(BaseModel):
    typename__: Literal["Program"] = Field(alias="__typename")


class GetChangeForReviewChangeEditsNodesChangesVariant(BaseModel):
    typename__: Literal["Variant"] = Field(alias="__typename")
    typename__: Literal["Variant"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalCategory(BaseModel):
    typename__: Literal["Category"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalComponent(BaseModel):
    typename__: Literal["Component"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalItem(BaseModel):
    typename__: Literal["Item"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalMaterial(BaseModel):
    typename__: Literal["Material"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalOrg(BaseModel):
    typename__: Literal["Org"] = Field(alias="__typename")


class GetChangeForReviewChangeEditsNodesOriginalPlace(BaseModel):
    typename__: Literal["Place"] = Field(alias="__typename")
    typename__: Literal["Place"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalProcess(BaseModel):
    typename__: Literal["Process"] = Field(alias="__typename")
    typename__: Literal["Process"] = Field(alias="__typename")
    id: str


class GetChangeForReviewChangeEditsNodesOriginalProgram(BaseModel):
    typename__: Literal["Program"] = Field(alias="__typename")


class GetChangeForReviewChangeEditsNodesOriginalVariant(BaseModel):
    typename__: Literal["Variant"] = Field(alias="__typename")
    typename__: Literal["Variant"] = Field(alias="__typename")
    id: str


GetChangeForReview.model_rebuild()
GetChangeForReviewChange.model_rebuild()
GetChangeForReviewChangeEdits.model_rebuild()
GetChangeForReviewChangeEditsNodes.model_rebuild()
