# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetComponentForReview(BaseModel):
    component: Optional["GetComponentForReviewComponent"]


class GetComponentForReviewComponent(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    primary_material: "GetComponentForReviewComponentPrimaryMaterial" = Field(
        alias="primaryMaterial"
    )
    materials: list["GetComponentForReviewComponentMaterials"]
    sources: "GetComponentForReviewComponentSources"


class GetComponentForReviewComponentPrimaryMaterial(BaseModel):
    id: str
    name: Optional[str]


class GetComponentForReviewComponentMaterials(BaseModel):
    material: "GetComponentForReviewComponentMaterialsMaterial"
    material_fraction: Optional[float] = Field(alias="materialFraction")


class GetComponentForReviewComponentMaterialsMaterial(BaseModel):
    id: str
    name: Optional[str]


class GetComponentForReviewComponentSources(BaseModel):
    nodes: Optional[list["GetComponentForReviewComponentSourcesNodes"]]


class GetComponentForReviewComponentSourcesNodes(BaseModel):
    source: "GetComponentForReviewComponentSourcesNodesSource"


class GetComponentForReviewComponentSourcesNodesSource(BaseModel):
    id: str
    content: Optional[Any]


GetComponentForReview.model_rebuild()
GetComponentForReviewComponent.model_rebuild()
GetComponentForReviewComponentMaterials.model_rebuild()
GetComponentForReviewComponentSources.model_rebuild()
GetComponentForReviewComponentSourcesNodes.model_rebuild()
