# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetCategoryForReview(BaseModel):
    category: Optional["GetCategoryForReviewCategory"]


class GetCategoryForReviewCategory(BaseModel):
    id: str
    name: str
    desc: Optional[str]
    parents: "GetCategoryForReviewCategoryParents"
    children: "GetCategoryForReviewCategoryChildren"
    items: "GetCategoryForReviewCategoryItems"


class GetCategoryForReviewCategoryParents(BaseModel):
    nodes: list["GetCategoryForReviewCategoryParentsNodes"]


class GetCategoryForReviewCategoryParentsNodes(BaseModel):
    id: str
    name: str


class GetCategoryForReviewCategoryChildren(BaseModel):
    nodes: list["GetCategoryForReviewCategoryChildrenNodes"]


class GetCategoryForReviewCategoryChildrenNodes(BaseModel):
    id: str
    name: str


class GetCategoryForReviewCategoryItems(BaseModel):
    nodes: list["GetCategoryForReviewCategoryItemsNodes"]


class GetCategoryForReviewCategoryItemsNodes(BaseModel):
    id: str
    name: Optional[str]


GetCategoryForReview.model_rebuild()
GetCategoryForReviewCategory.model_rebuild()
GetCategoryForReviewCategoryParents.model_rebuild()
GetCategoryForReviewCategoryChildren.model_rebuild()
GetCategoryForReviewCategoryItems.model_rebuild()
