# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetComponentSchema(BaseModel):
    component_schema: Optional["GetComponentSchemaComponentSchema"] = Field(
        alias="componentSchema"
    )


class GetComponentSchemaComponentSchema(BaseModel):
    create: Optional["GetComponentSchemaComponentSchemaCreate"]
    update: Optional["GetComponentSchemaComponentSchemaUpdate"]


class GetComponentSchemaComponentSchemaCreate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


class GetComponentSchemaComponentSchemaUpdate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


GetComponentSchema.model_rebuild()
GetComponentSchemaComponentSchema.model_rebuild()
