# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetMaterialForReview(BaseModel):
    material: Optional["GetMaterialForReviewMaterial"]


class GetMaterialForReviewMaterial(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]


GetMaterialForReview.model_rebuild()
