# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetVariantForReview(BaseModel):
    variant: Optional["GetVariantForReviewVariant"]


class GetVariantForReviewVariant(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    items: "GetVariantForReviewVariantItems"
    components: "GetVariantForReviewVariantComponents"
    orgs: "GetVariantForReviewVariantOrgs"


class GetVariantForReviewVariantItems(BaseModel):
    nodes: Optional[list["GetVariantForReviewVariantItemsNodes"]]


class GetVariantForReviewVariantItemsNodes(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]


class GetVariantForReviewVariantComponents(BaseModel):
    nodes: Optional[list["GetVariantForReviewVariantComponentsNodes"]]


class GetVariantForReviewVariantComponentsNodes(BaseModel):
    component: "GetVariantForReviewVariantComponentsNodesComponent"
    quantity: Optional[float]
    unit: Optional[str]


class GetVariantForReviewVariantComponentsNodesComponent(BaseModel):
    id: str
    name: Optional[str]


class GetVariantForReviewVariantOrgs(BaseModel):
    nodes: Optional[list["GetVariantForReviewVariantOrgsNodes"]]


class GetVariantForReviewVariantOrgsNodes(BaseModel):
    org: "GetVariantForReviewVariantOrgsNodesOrg"
    role: Optional[str]


class GetVariantForReviewVariantOrgsNodesOrg(BaseModel):
    id: str
    name: str


GetVariantForReview.model_rebuild()
GetVariantForReviewVariant.model_rebuild()
GetVariantForReviewVariantItems.model_rebuild()
GetVariantForReviewVariantComponents.model_rebuild()
GetVariantForReviewVariantComponentsNodes.model_rebuild()
GetVariantForReviewVariantOrgs.model_rebuild()
GetVariantForReviewVariantOrgsNodes.model_rebuild()
