# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetCurrentUser(BaseModel):
    me: Optional["GetCurrentUserMe"]


class GetCurrentUserMe(BaseModel):
    id: str
    email: str
    name: Optional[str]
    username: str


GetCurrentUser.model_rebuild()
