# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from .base_model import BaseModel


class GetItemForReview(BaseModel):
    item: Optional["GetItemForReviewItem"]


class GetItemForReviewItem(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    categories: "GetItemForReviewItemCategories"
    variants: "GetItemForReviewItemVariants"


class GetItemForReviewItemCategories(BaseModel):
    nodes: Optional[list["GetItemForReviewItemCategoriesNodes"]]


class GetItemForReviewItemCategoriesNodes(BaseModel):
    id: str
    name: str


class GetItemForReviewItemVariants(BaseModel):
    nodes: Optional[list["GetItemForReviewItemVariantsNodes"]]


class GetItemForReviewItemVariantsNodes(BaseModel):
    id: str
    name: Optional[str]


GetItemForReview.model_rebuild()
GetItemForReviewItem.model_rebuild()
GetItemForReviewItemCategories.model_rebuild()
GetItemForReviewItemVariants.model_rebuild()
