# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetCategorySchema(BaseModel):
    category_schema: Optional["GetCategorySchemaCategorySchema"] = Field(
        alias="categorySchema"
    )


class GetCategorySchemaCategorySchema(BaseModel):
    create: Optional["GetCategorySchemaCategorySchemaCreate"]
    update: Optional["GetCategorySchemaCategorySchemaUpdate"]


class GetCategorySchemaCategorySchemaCreate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


class GetCategorySchemaCategorySchemaUpdate(BaseModel):
    schema_: Optional[Any] = Field(alias="schema")


GetCategorySchema.model_rebuild()
GetCategorySchemaCategorySchema.model_rebuild()
