# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Any, Optional

from .base_model import BaseModel


class GetVariantForReview(BaseModel):
    variant: Optional["GetVariantForReviewVariant"]


class GetVariantForReviewVariant(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]
    items: "GetVariantForReviewVariantItems"
    components: "GetVariantForReviewVariantComponents"
    orgs: "GetVariantForReviewVariantOrgs"
    sources: "GetVariantForReviewVariantSources"


class GetVariantForReviewVariantItems(BaseModel):
    nodes: list["GetVariantForReviewVariantItemsNodes"]


class GetVariantForReviewVariantItemsNodes(BaseModel):
    id: str
    name: Optional[str]
    desc: Optional[str]


class GetVariantForReviewVariantComponents(BaseModel):
    nodes: list["GetVariantForReviewVariantComponentsNodes"]


class GetVariantForReviewVariantComponentsNodes(BaseModel):
    component: "GetVariantForReviewVariantComponentsNodesComponent"
    quantity: Optional[float]
    unit: Optional[str]


class GetVariantForReviewVariantComponentsNodesComponent(BaseModel):
    id: str
    name: Optional[str]


class GetVariantForReviewVariantOrgs(BaseModel):
    nodes: list["GetVariantForReviewVariantOrgsNodes"]


class GetVariantForReviewVariantOrgsNodes(BaseModel):
    org: "GetVariantForReviewVariantOrgsNodesOrg"
    role: Optional[str]


class GetVariantForReviewVariantOrgsNodesOrg(BaseModel):
    id: str
    name: str


class GetVariantForReviewVariantSources(BaseModel):
    nodes: list["GetVariantForReviewVariantSourcesNodes"]


class GetVariantForReviewVariantSourcesNodes(BaseModel):
    source: "GetVariantForReviewVariantSourcesNodesSource"


class GetVariantForReviewVariantSourcesNodesSource(BaseModel):
    id: str
    content: Optional[Any]


GetVariantForReview.model_rebuild()
GetVariantForReviewVariant.model_rebuild()
GetVariantForReviewVariantItems.model_rebuild()
GetVariantForReviewVariantComponents.model_rebuild()
GetVariantForReviewVariantComponentsNodes.model_rebuild()
GetVariantForReviewVariantOrgs.model_rebuild()
GetVariantForReviewVariantOrgsNodes.model_rebuild()
GetVariantForReviewVariantSources.model_rebuild()
GetVariantForReviewVariantSourcesNodes.model_rebuild()
