# Generated by ariadne-codegen
# Source: f/graphql/schema.gql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ChangeStatus, SourceType, TagType


class ComponentMaterialInput(BaseModel):
    id: str
    material_fraction: Optional[float] = Field(alias="materialFraction", default=None)
    "Fraction of this material in the component (0–1)"


class ComponentRegionInput(BaseModel):
    id: str


class ComponentTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


class CreateCategoryInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_short: Optional[str] = Field(alias="descShort", default=None)
    desc_short_tr: Optional[list["TranslatedInput"]] = Field(
        alias="descShortTr", default=None
    )
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"


class CreateChangeInput(BaseModel):
    description: Optional[str] = None
    sources: Optional[list[str]] = None
    status: Optional[ChangeStatus] = None
    title: Optional[str] = None


class CreateComponentInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    materials: Optional[list["ComponentMaterialInput"]] = None
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    physical: Optional[Any] = None
    primary_material: Optional["ComponentMaterialInput"] = Field(
        alias="primaryMaterial", default=None
    )
    region: Optional["ComponentRegionInput"] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    tags: Optional[list["ComponentTagsInput"]] = None
    visual: Optional[Any] = None


class CreateItemInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    categories: Optional[list["ItemCategoriesInput"]] = None
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    tags: Optional[list["ItemTagsInput"]] = None


class CreateOrgInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    avatar_url: Optional[str] = Field(alias="avatarURL", default=None)
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: str
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    slug: str
    website_url: Optional[str] = Field(alias="websiteURL", default=None)


class CreateProcessInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    efficiency: Optional[Any] = None
    instructions: Optional[Any] = None
    intent: str
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    material: Optional["ProcessMaterialInput"] = None
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    org: Optional["ProcessOrgInput"] = None
    place: Optional["ProcessPlaceInput"] = None
    region: Optional["ProcessRegionInput"] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    rules: Optional[Any] = None
    variant: Optional["ProcessVariantInput"] = None


class CreateSourceInput(BaseModel):
    content: Optional[Any] = None
    content_url: Optional[str] = Field(alias="contentURL", default=None)
    location: Optional[str] = None
    metadata: Optional[Any] = None
    type_: SourceType = Field(alias="type")


class CreateTagDefinitionInput(BaseModel):
    bg_color: Optional[str] = Field(alias="bgColor", default=None)
    desc: Optional[str] = None
    image: Optional[str] = None
    meta_template: Optional[Any] = Field(alias="metaTemplate", default=None)
    name: str
    type_: TagType = Field(alias="type")


class CreateVariantInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    code: Optional[str] = None
    "Manufacturer or product code for this variant"
    components: Optional[list["VariantComponentsInput"]] = None
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    items: Optional[list["VariantItemsInput"]] = None
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    orgs: Optional[list["VariantOrgsInput"]] = None
    region: Optional["VariantRegionsInput"] = None
    regions: Optional[list["VariantRegionsInput"]] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    tags: Optional[list["VariantTagsInput"]] = None


class DeleteInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    apply: Optional[bool] = None
    change: Optional["CreateChangeInput"] = None
    change_id: Optional[str] = Field(alias="changeID", default=None)
    id: str
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)


class ItemCategoriesInput(BaseModel):
    id: str


class ItemTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


class ProcessMaterialInput(BaseModel):
    id: str


class ProcessOrgInput(BaseModel):
    id: str


class ProcessPlaceInput(BaseModel):
    id: str


class ProcessRegionInput(BaseModel):
    id: str


class ProcessVariantInput(BaseModel):
    id: str


class SourceInput(BaseModel):
    id: str
    meta: Optional[Any] = None


class TranslatedInput(BaseModel):
    """A translated text value for a specific language"""

    auto: bool = False
    "Whether this translation was generated automatically"
    lang: str
    'BCP 47 language code (e.g. "en", "fr-CA")'
    text: Optional[str] = None


class UpdateCategoryInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_short: Optional[str] = Field(alias="descShort", default=None)
    desc_short_tr: Optional[list["TranslatedInput"]] = Field(
        alias="descShortTr", default=None
    )
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    id: str
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"


class UpdateChangeInput(BaseModel):
    description: Optional[str] = None
    id: str
    sources: Optional[list[str]] = None
    status: Optional[ChangeStatus] = None
    title: Optional[str] = None


class UpdateComponentInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    add_tags: Optional[list["ComponentTagsInput"]] = Field(
        alias="addTags", default=None
    )
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    id: str
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    materials: Optional[list["ComponentMaterialInput"]] = None
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    physical: Optional[Any] = None
    primary_material: Optional["ComponentMaterialInput"] = Field(
        alias="primaryMaterial", default=None
    )
    region: Optional["ComponentRegionInput"] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    remove_tags: Optional[list[str]] = Field(alias="removeTags", default=None)
    tags: Optional[list["ComponentTagsInput"]] = None
    visual: Optional[Any] = None


class UpdateItemInput(BaseModel):
    add_categories: Optional[list["ItemCategoriesInput"]] = Field(
        alias="addCategories", default=None
    )
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    add_tags: Optional[list["ItemTagsInput"]] = Field(alias="addTags", default=None)
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    categories: Optional[list["ItemCategoriesInput"]] = None
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    id: str
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    remove_categories: Optional[list[str]] = Field(
        alias="removeCategories", default=None
    )
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    remove_tags: Optional[list[str]] = Field(alias="removeTags", default=None)
    tags: Optional[list["ItemTagsInput"]] = None


class UpdateOrgInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    avatar_url: Optional[str] = Field(alias="avatarURL", default=None)
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    id: str
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    slug: Optional[str] = None
    website_url: Optional[str] = Field(alias="websiteURL", default=None)


class UpdateProcessInput(BaseModel):
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    efficiency: Optional[Any] = None
    id: str
    instructions: Optional[Any] = None
    intent: Optional[str] = None
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    material: Optional["ProcessMaterialInput"] = None
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    org: Optional["ProcessOrgInput"] = None
    place: Optional["ProcessPlaceInput"] = None
    region: Optional["ProcessRegionInput"] = None
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    rules: Optional[Any] = None
    variant: Optional["ProcessVariantInput"] = None


class UpdateSourceInput(BaseModel):
    content: Optional[Any] = None
    content_url: Optional[str] = Field(alias="contentURL", default=None)
    id: str
    location: Optional[str] = None
    metadata: Optional[Any] = None
    type_: Optional[SourceType] = Field(alias="type", default=None)


class UpdateTagDefinitionInput(BaseModel):
    bg_color: Optional[str] = Field(alias="bgColor", default=None)
    desc: Optional[str] = None
    id: str
    image: Optional[str] = None
    meta_template: Optional[Any] = Field(alias="metaTemplate", default=None)
    name: Optional[str] = None
    type_: Optional[TagType] = Field(alias="type", default=None)


class UpdateVariantInput(BaseModel):
    add_components: Optional[list["VariantComponentsInput"]] = Field(
        alias="addComponents", default=None
    )
    add_items: Optional[list["VariantItemsInput"]] = Field(
        alias="addItems", default=None
    )
    add_orgs: Optional[list["VariantOrgsInput"]] = Field(alias="addOrgs", default=None)
    add_regions: Optional[list["VariantRegionsInput"]] = Field(
        alias="addRegions", default=None
    )
    add_sources: Optional[list["SourceInput"]] = Field(alias="addSources", default=None)
    "Sources to associate with this change"
    add_tags: Optional[list["VariantTagsInput"]] = Field(alias="addTags", default=None)
    apply: Optional[bool] = None
    "If true, immediately apply (merge) the change after creation"
    change: Optional["CreateChangeInput"] = None
    "Details for a new change to create for this edit"
    change_id: Optional[str] = Field(alias="changeID", default=None)
    "ID of an existing change to add this edit to"
    code: Optional[str] = None
    components: Optional[list["VariantComponentsInput"]] = None
    desc: Optional[str] = None
    desc_tr: Optional[list["TranslatedInput"]] = Field(alias="descTr", default=None)
    id: str
    image_url: Optional[str] = Field(alias="imageURL", default=None)
    items: Optional[list["VariantItemsInput"]] = None
    lang: Optional[str] = None
    'Language code for text input fields (BCP 47, e.g. "en")'
    name: Optional[str] = None
    name_tr: Optional[list["TranslatedInput"]] = Field(alias="nameTr", default=None)
    orgs: Optional[list["VariantOrgsInput"]] = None
    region: Optional["VariantRegionsInput"] = None
    remove_components: Optional[list[str]] = Field(
        alias="removeComponents", default=None
    )
    remove_items: Optional[list[str]] = Field(alias="removeItems", default=None)
    remove_orgs: Optional[list[str]] = Field(alias="removeOrgs", default=None)
    remove_regions: Optional[list[str]] = Field(alias="removeRegions", default=None)
    remove_sources: Optional[list[str]] = Field(alias="removeSources", default=None)
    "IDs of sources to remove from this change"
    remove_tags: Optional[list[str]] = Field(alias="removeTags", default=None)
    tags: Optional[list["VariantTagsInput"]] = None


class VariantComponentsInput(BaseModel):
    id: str
    quantity: Optional[float] = None
    "Quantity of this component in the variant"
    unit: Optional[str] = None
    "Unit of measurement for the component quantity"


class VariantItemsInput(BaseModel):
    id: str


class VariantOrgsInput(BaseModel):
    id: str


class VariantRegionsInput(BaseModel):
    id: str


class VariantTagsInput(BaseModel):
    id: str
    meta: Optional[Any] = None


CreateCategoryInput.model_rebuild()
CreateComponentInput.model_rebuild()
CreateItemInput.model_rebuild()
CreateOrgInput.model_rebuild()
CreateProcessInput.model_rebuild()
CreateVariantInput.model_rebuild()
DeleteInput.model_rebuild()
UpdateCategoryInput.model_rebuild()
UpdateComponentInput.model_rebuild()
UpdateItemInput.model_rebuild()
UpdateOrgInput.model_rebuild()
UpdateProcessInput.model_rebuild()
UpdateVariantInput.model_rebuild()
