# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class LinkSource(BaseModel):
    link_source: "LinkSourceLinkSource" = Field(alias="linkSource")


class LinkSourceLinkSource(BaseModel):
    source: Optional["LinkSourceLinkSourceSource"]


class LinkSourceLinkSourceSource(BaseModel):
    id: str


LinkSource.model_rebuild()
LinkSourceLinkSource.model_rebuild()
