# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class Search(BaseModel):
    search: "SearchSearch"


class SearchSearch(BaseModel):
    nodes: Optional[
        list[
            Annotated[
                Union[
                    "SearchSearchNodesCategory",
                    "SearchSearchNodesComponent",
                    "SearchSearchNodesItem",
                    "SearchSearchNodesMaterial",
                    "SearchSearchNodesOrg",
                    "SearchSearchNodesPlace",
                    "SearchSearchNodesRegion",
                    "SearchSearchNodesVariant",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ]


class SearchSearchNodesCategory(BaseModel):
    typename__: Literal["Category"] = Field(alias="__typename")
    id: str
    label: str
    desc: Optional[str]
    desc_short: Optional[str] = Field(alias="descShort")


class SearchSearchNodesComponent(BaseModel):
    typename__: Literal["Component"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    desc: Optional[str]


class SearchSearchNodesItem(BaseModel):
    typename__: Literal["Item"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    desc: Optional[str]


class SearchSearchNodesMaterial(BaseModel):
    typename__: Literal["Material"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    desc: Optional[str]


class SearchSearchNodesOrg(BaseModel):
    typename__: Literal["Org"] = Field(alias="__typename")
    id: str
    label: str
    desc: Optional[str]
    slug: str


class SearchSearchNodesPlace(BaseModel):
    typename__: Literal["Place"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    desc: Optional[str]


class SearchSearchNodesRegion(BaseModel):
    typename__: Literal["Region"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    placetype: str


class SearchSearchNodesVariant(BaseModel):
    typename__: Literal["Variant"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    desc: Optional[str]


Search.model_rebuild()
SearchSearch.model_rebuild()
