# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ChangeStatus


class UpdateChangeStatus(BaseModel):
    update_change: Optional["UpdateChangeStatusUpdateChange"] = Field(
        alias="updateChange"
    )


class UpdateChangeStatusUpdateChange(BaseModel):
    change: Optional["UpdateChangeStatusUpdateChangeChange"]


class UpdateChangeStatusUpdateChangeChange(BaseModel):
    id: str
    status: ChangeStatus


UpdateChangeStatus.model_rebuild()
UpdateChangeStatusUpdateChange.model_rebuild()
