# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateProcess(BaseModel):
    update_process: Optional["UpdateProcessUpdateProcess"] = Field(
        alias="updateProcess"
    )


class UpdateProcessUpdateProcess(BaseModel):
    process: Optional["UpdateProcessUpdateProcessProcess"]
    change: Optional["UpdateProcessUpdateProcessChange"]


class UpdateProcessUpdateProcessProcess(BaseModel):
    id: str
    name: Optional[str]


class UpdateProcessUpdateProcessChange(BaseModel):
    id: str


UpdateProcess.model_rebuild()
UpdateProcessUpdateProcess.model_rebuild()
