# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateComponent(BaseModel):
    update_component: Optional["UpdateComponentUpdateComponent"] = Field(
        alias="updateComponent"
    )


class UpdateComponentUpdateComponent(BaseModel):
    component: Optional["UpdateComponentUpdateComponentComponent"]
    change: Optional["UpdateComponentUpdateComponentChange"]


class UpdateComponentUpdateComponentComponent(BaseModel):
    id: str
    name: Optional[str]


class UpdateComponentUpdateComponentChange(BaseModel):
    id: str


UpdateComponent.model_rebuild()
UpdateComponentUpdateComponent.model_rebuild()
