# Generated by ariadne-codegen
# Source: f/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateCategory(BaseModel):
    update_category: Optional["UpdateCategoryUpdateCategory"] = Field(
        alias="updateCategory"
    )


class UpdateCategoryUpdateCategory(BaseModel):
    category: Optional["UpdateCategoryUpdateCategoryCategory"]
    change: Optional["UpdateCategoryUpdateCategoryChange"]


class UpdateCategoryUpdateCategoryCategory(BaseModel):
    id: str
    name: str


class UpdateCategoryUpdateCategoryChange(BaseModel):
    id: str


UpdateCategory.model_rebuild()
UpdateCategoryUpdateCategory.model_rebuild()
