mutation AddCategory($input: CreateCategoryInput!) {
  createCategory(input: $input) {
    category {
      id
      name
    }
    change {
      id
    }
  }
}

mutation UpdateCategory($input: UpdateCategoryInput!) {
  updateCategory(input: $input) {
    category {
      id
      name
    }
    change {
      id
    }
  }
}

query GetRootCategory {
  categoryRoot {
    id
  }
}

query GetCategoryForReview($id: ID!) {
  category(id: $id) {
    id
    name
    desc
    parents(first: 5) {
      nodes {
        id
        name
      }
    }
    children(first: 10) {
      nodes {
        id
        name
      }
    }
    items(first: 10) {
      nodes {
        id
        name
      }
    }
  }
}
