query GetComponentForReview($id: ID!) {
  component(id: $id) {
    id
    name
    desc
    primaryMaterial {
      id
      name
    }
    materials {
      material {
        id
        name
      }
      materialFraction
    }
    sources(first: 10) {
      nodes {
        source {
          id
          content
        }
      }
    }
  }
}

mutation AddComponent($input: CreateComponentInput!) {
  createComponent(input: $input) {
    component {
      id
      name
    }
    change {
      id
    }
  }
}

mutation UpdateComponent($input: UpdateComponentInput!) {
  updateComponent(input: $input) {
    component {
      id
      name
    }
    change {
      id
    }
  }
}
