query GetItemForReview($id: ID!) {
  item(id: $id) {
    id
    name
    desc
    categories(first: 10) {
      nodes {
        id
        name
      }
    }
    variants(first: 10) {
      nodes {
        id
        name
      }
    }
  }
}

query GetItemForLink($id: ID!) {
  item(id: $id) {
    id
    name
    desc
    categories(first: 5) {
      nodes {
        id
        name
      }
    }
  }
}

mutation AddItem($input: CreateItemInput!) {
  createItem(input: $input) {
    item {
      id
      name
      desc
    }
    change {
      id
    }
  }
}

mutation UpdateItem($input: UpdateItemInput!) {
  updateItem(input: $input) {
    item {
      id
      name
      desc
    }
    change {
      id
    }
  }
}
