mutation AddProcess($input: CreateProcessInput!) {
  createProcess(input: $input) {
    process {
      id
      name
    }
    change {
      id
    }
  }
}

mutation UpdateProcess($input: UpdateProcessInput!) {
  updateProcess(input: $input) {
    process {
      id
      name
    }
    change {
      id
    }
  }
}

query GetProcessForReview($id: ID!) {
  process(id: $id) {
    id
    name
    desc
    intent
    material {
      id
      name
    }
    org {
      id
      name
    }
    place {
      id
      name
    }
    region {
      id
    }
    variant {
      id
      name
    }
    efficiency {
      efficiency
      equivalency
      valueRatio
    }
    sources(first: 10) {
      nodes {
        source {
          id
          content
        }
      }
    }
  }
}
